### ISSUE TITLE
add draw evenience

### ISSUE THREAD

**Issue by BojDom** [rundef/node-poker-odds-calculator#1]
Very nice project , but it should also handle draw cases, currently
`node_modules/.bin/poker-odds-calculator AdAh AcAs`
outputs 
Player #1 - Ah Ad - ~2%
Player #2 - As Ac - ~98%

**Comment by rundef** [comment]
Hi,
Yes you are right, currently the ties are not handled by this package.
I'll look into it when I get the time.

Thanks !

**Comment by rundef** [comment]
Thanks for the help, I just published v0.2.0 on npm.
