### ISSUE TITLE
Is it possible to predict Odds for one hand and table without second player

### ISSUE THREAD

**Issue by ch3ll0v3k** [rundef/node-poker-odds-calculator#3]
Is it possible to predict Odds for one hand and table without second player.

If i try it, it show all ways 100%, which is not really correct

Thank you!

**Comment by rundef** [comment]
Hi,
I'm not sure what you mean ?
If there's only one player in a game, than that player automatically wins, no ? :)

**Comment by ch3ll0v3k** [comment]
;))   I mean, to make prediction based only on my hands and cards on the table.

**Comment by Mohsen7s** [comment]
Yea this would be a great feature

**Comment by CookPete** [comment]
Sorry to hijack the issue with a shameless plug but I've just published [`poker-odds`](https://github.com/CookPete/poker-odds) that does this. Pass in one hand and it will return the probability of hitting the different possible hands, or use `--possibilities` when passing in multiple hands to return the probabilities for each hand:

![--possibilities example](https://user-images.githubusercontent.com/1926029/35532961-e73f5d18-0533-11e8-86f0-22c17c2d2dda.png)
