### ISSUE TITLE
Pocket pair and two pairs on the board

### ISSUE THREAD

**Issue by Brandoning** [rundef/node-poker-odds-calculator#4]
When there's two pairs on the board, and a pocket pair of higher value it does not pick up the players pocket pair.

Instead it ranks another player with nothing as the winner.

![image005](https://user-images.githubusercontent.com/5629295/34955561-f0427124-fa1c-11e7-899b-540863443700.png)

If you remove a pair from the board, the hands are then ranked correctly.

![image006](https://user-images.githubusercontent.com/5629295/34955575-07601226-fa1d-11e7-98f2-62c2038a7429.png)

I am looking in to this myself right now but would also appreciate the authors help if he still monitors this project.

**Comment by rundef** [comment]
Hi @Brandoning,

Thanks for reporting this bug. It is fixed in the version **0.2.1**

**Comment by Brandoning** [comment]
Thanks for that! Works perfect
